
## This rule redirects to an external API, signing requests with a secret

[[redirects]]
  from = "/youdao"
  to = "http://fanyi.youdao.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
