
## This rule redirects to an external API, signing requests with a secret

[[redirects]]
  from = "/youdao/*"
  to = "https://fanyi.youdao.com"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

